### PR TITLE
Added 4 attributes

### PR DESCRIPTION
**Pull request by FedericoHeichou**
I just added 4 attributes for anime sidebar and updated version in setup.py

Licensors, Studios, Premiered and Source.

### CODE REVIEW

**Comment by pushrbx** [comment]
Will look into it this week. Thanks!

**Comment by FedericoHeichou** [comment]
I did other modifications on "heichou" brench if you want give a look but something is only for anime and media. If you want I can merge it too but I added a sleep timer for flooding protection (I'm actually downloading all anime database and without a sleep it returns error 421, but I implemented it pretty bad, your choice, it actually work)

**Comment by pushrbx** [comment]
This software is not really designed for crawling imo. Im using it with scrapy. (instead of scrapy's built-in parser)

**Comment by FedericoHeichou** [comment]
I don't know but I already downloaded all anime in mal into a csv (with needed information) and the script daily checks for update.

This is a onetime crawling, sometimes it update some anime, but it's not a problem.
I will use this library just for checking anime ids in a user's mal (the computation is done locally with the already downloaded csv), so it's worth, no more crawling is needed for me

**Comment by pushrbx** [comment]
Could you please add tests for these?

**Comment by pushrbx** [comment]
One more thing: I've fixed the tests on travis, please merge in the latest from master. When you run the tests locally use `-a '!obsolete'` argument for nose. See the `travis.yaml` file on master.

**Comment by FedericoHeichou** [comment]
Committed. But there is a problem, I don't know how avoid "HTML: Too Many Requests", so I launched the test until it never fails my 4 new tests.
Anyway, I just added these 4 tests.

Commits like
- Fixed aring date without day (b76db7b)
- Fixed none score_stats (974f16b)
I don't think need to be tested

**Comment by pushrbx** [comment]
It looks ok, but just one thing to note:
The `u` marker for strings is not really needed as we are targeting python 3. All strings are unicode by default.

**Comment by FedericoHeichou** [comment]
> It looks ok, but just one thing to note:
> The `u` marker for strings is not really needed as we are targeting python 3. All strings are unicode by default.

Yes, I know, but I saw all file wrote in that way so I keep `u` to have everything homogeneous, else usually I just use `"` (double quotes), I don't like `'` (apex)

**Pull request merged**
